# Generated by Django 4.2.5 on 2023-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='robot_model',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='robot_version',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
